/*
import 'package:get/get.dart';
class StringsAssetsConstants {
static String get givecreadentialtosigninyouraccount{return "giveCreadentialToSignInYourAccount".tr;}
static String get givecreadentialtosignupyouraccount{return "giveCreadentialToSignUpYourAccount".tr;}
static String get email{return "email".tr;}
static String get password{return "password".tr;}
static String get typeyour{return "typeYour".tr;}
static String get rememberme{return "rememberMe".tr;}
static String get forgotpassword{return "forgotPassword".tr;}
static String get signin{return "signIn".tr;}
static String get orcontinuewith{return "orContinueWith".tr;}
static String get donthaveanaccount{return "dontHaveAnAccount".tr;}
static String get signup{return "signUp".tr;}
static String get datavalidation{return "datavalidation".tr;}
static String get emailvalidation{return "emailValidation".tr;}
static String get passwordvalidation{return "passwordValidation".tr;}
static String get work1{return "work1".tr;}
static String get success_message{return "success_message".tr;}
static String get congrats{return "congrats".tr;}
static String get add_new_order{return "add_new_order".tr;}
static String get back_to_main{return "back_to_main".tr;}
static String get rate_order{return "rate_order".tr;}
static String get rate_order_number{return "rate_order_number".tr;}
static String get add_comment{return "add_comment".tr;}
static String get what_is_your_rating{return "what_is_your_rating".tr;}
static String get previous_orders{return "previous_orders".tr;}
static String get order_number{return "order_number".tr;}
static String get required_services{return "required_services".tr;}
static String get order_status{return "order_status".tr;}
static String get under_review{return "under_review".tr;}
static String get done{return "done".tr;}
static String get underway{return "underway".tr;}
static String get fail{return "fail".tr;}
static String get science{return "science".tr;}
static String get day{return "day".tr;}
static String get days{return "days".tr;}
// new code
static String get datavalidate{return "dataValidate".tr;}
static String get currency{return "currency".tr;}
static String get send{return "send".tr;}
static String get total_prices{return "total_prices".tr;}
static String get month{return "month".tr;}
static String get months{return "months".tr;}
static String get year{return "year".tr;}
static String get years{return "years".tr;}
static String get od_step1{return "od_step1".tr;}
static String get od_step2{return "od_step2".tr;}
static String get od_step3{return "od_step3".tr;}
static String get od_step4{return "od_step4".tr;}
static String get notifications{return "notifications".tr;}
static String get nonotifications{return "noNotifications".tr;}
static String get since{return "since".tr;}
static String get services{return "services".tr;}
static String get hello{return "hello".tr;}
static String get ourservices{return "ourServices".tr;}
static String get seemore{return "seeMore".tr;}
static String get otherservices{return "otherServices".tr;}
static String get reset_password{return "reset_password".tr;}
static String get email_request_hint{return "email_request_hint".tr;}
static String get type_your_email{return "type_your_email".tr;}
static String get verification{return "verification".tr;}
static String get reset_now{return "reset_now".tr;}
static String get code_sent{return "code_sent".tr;}
static String get resend{return "resend".tr;}
static String get confirm_password{return "confirm_password".tr;}
static String get type_your_password{return "type_your_password".tr;}
static String get connectedtointernet{return "connectedToInternet".tr;}
static String get nointernetconnection{return "noInternetConnection".tr;}
static String get searchjobeasierandmoreeffective{return "searchJobEasierAndMoreEffective".tr;}
static String get makeyourexperienceofsearchingjobmoreeasierandmoreeffective{return "makeYourExperienceOfSearchingJobMoreEasierAndMoreEffective".tr;}
static String get next{return "next".tr;}
static String get skip{return "skip".tr;}
static String get getstarted{return "getStarted".tr;}
static String get applyforjobanywhereandanytime{return "applyForJobAnywhereAndAnytime".tr;}
static String get jobfilmakesyoucanapplyforjobfromanywhereandanytime{return "jobfilMakesYouCanApplyForJobFromAnywhereAndAnytime".tr;}
static String get helpfindtherightjobwithyourdesire{return "helpFindTheRightJobWithYourDesire".tr;}
static String get jobfilcanhelpuoufindtherightjobwithyourdesire{return "JobfilCanHelpUouFindTheRightJobWithYourDesire".tr;}
static String get confirm_password_validation{return "confirm_password_validation".tr;}
static String get get_code_in{return "get_code_in".tr;}
static String get fullname{return "fullName".tr;}
static String get passwordconfirmation{return "passwordConfirmation".tr;}
static String get fullnamevalidation{return "fullNameValidation".tr;}
static String get alreadyhaveanaccount{return "alreadyHaveAnAccount".tr;}
static String get passwordconfirmationvalidation{return "passwordConfirmationValidation".tr;}
static String get filter{return "filter".tr;}
static String get category{return "category".tr;}
static String get chooseyourcategory{return "chooseYourCategory".tr;}
static String get location{return "location".tr;}
static String get writeyourlocation{return "writeYourLocation".tr;}
static String get minsalary{return "minSalary".tr;}
static String get maxsalary{return "maxSalary".tr;}
static String get jobtype{return "jobType".tr;}
static String get applyfilter{return "applyFilter".tr;}
static String get searchjob{return "searchJob".tr;}
static String get recentsearches{return "recentSearches".tr;}
static String get jobsfound{return "jobsFound".tr;}
static String get searchhint{return "searchHint".tr;}
static String get portfolio{return "portfolio".tr;}
static String get upload_cv{return "upload_cv".tr;}
static String get attach_format{return "attach_format".tr;}
static String get browse_files{return "browse_files".tr;}
static String get letter{return "letter".tr;}
static String get write_something{return "write_something".tr;}
static String get apply_this_job{return "apply_this_job".tr;}
static String get applied{return "applied".tr;}
static String get applied_successfully{return "applied_successfully".tr;}
static String get see_applied_job{return "see_applied_job".tr;}
static String get success{return "success".tr;}
static String get apply_job{return "apply_job".tr;}
static String get tap_to_upload{return "tap_to_upload".tr;}
static String get long_press_to_delete{return "long_press_to_delete".tr;}
static String get file_deleted{return "file_deleted".tr;}
static String get welcomeback{return "welcomeBack".tr;}
static String get search{return "search".tr;}
static String get letsfindnewjobsuitableforyou{return "letsFindNewJobSuitableForYou".tr;}
static String get learnmore{return "learnMore".tr;}
static String get browsebycategory{return "browseByCategory".tr;}
static String get suggestedjobs{return "suggestedJobs".tr;}
static String get apply{return "apply".tr;}
static String get search_applications{return "search_applications".tr;}
static String get applied_job{return "applied_job".tr;}
static String get your_applications{return "your_applications".tr;}
static String get offer_letter{return "offer_letter".tr;}
static String get team_matching{return "team_matching".tr;}
static String get final_hr_interview{return "final_hr_interview".tr;}
static String get tech_interview{return "tech_interview".tr;}
static String get screening_interview{return "screening_interview".tr;}
static String get reviewed_by{return "reviewed_by".tr;}
static String get application_submitted{return "application_submitted".tr;}
static String get canceled{return "canceled".tr;}
static String get view_application{return "view_application".tr;}
static String get delivered{return "delivered".tr;}
static String get on_the_way{return "on_the_way".tr;}
static String get track_application{return "track_application".tr;}
static String get recentjobs{return "recentJobs".tr;}
static String get details{return "details".tr;}
static String get jobdescription{return "jobDescription".tr;}
static String get company{return "company".tr;}
static String get review{return "review".tr;}
static String get abouttherole{return "aboutTheRole".tr;}
static String get requirementskillfortherole{return "requirementSkillForTheRole".tr;}
static String get aboutthiscompany{return "aboutThisCompany".tr;}
static String get skillassasment{return "skillAssasment".tr;}
static String get skilltest{return "skillTest".tr;}
static String get startskillassasment{return "startSkillAssasment".tr;}
static String get backtoskilltest{return "backToSkillTest".tr;}
static String get question{return "question".tr;}
static String get selectananswer{return "selectAnAnswer".tr;}
static String get textsuccess{return "textSuccess".tr;}
static String get emptytest{return "emptyTest".tr;}
static String get recentsearchesdesc{return "recentSearchesDesc".tr;}
static String get emptytestdesc{return "emptyTestDesc".tr;}
static String get youhavesuccessfullytopupthewallet{return "youHaveSuccessfullyTopUpTheWallet".tr;}
static String get setupprofile{return "setUpProfile".tr;}
static String get personalinformation{return "personalInformation".tr;}
static String get contactnumber{return "contactNumber".tr;}
static String get dateofbirth{return "dateOfBirth".tr;}
static String get gender{return "gender".tr;}
static String get continuenow{return "continueNow".tr;}
static String get male{return "male".tr;}
static String get female{return "female".tr;}
static String get selectdateofbirth{return "selectDateOfBirth".tr;}
static String get selectyourgender{return "selectYourGender".tr;}
static String get typeyouremail{return "typeYourEmail".tr;}
static String get typeyourfullname{return "typeYourFullName".tr;}
static String get interest{return "interest".tr;}
static String get interestsubtext{return "interestSubText".tr;}
static String get interesttxt{return "interestTxt".tr;}
static String get confirmnewaccount{return "confirmNewAccount".tr;}
static String get confirmnewaccounttxt{return "confirmNewAccountTxt".tr;}
static String get welcome{return "welcome".tr;}
static String get createmyaccount{return "createMyAccount".tr;}
static String get youraccountset{return "yourAccountSet".tr;}
static String get youraccountsettext{return "yourAccountSetText".tr;}
static String get backtohome{return "backToHome".tr;}
static String get basedon{return "basedOn".tr;}
static String get reviews{return "reviews".tr;}
static String get employeereviews{return "employeeReviews".tr;}
static String get profile{return "profile".tr;}
static String get workexperience{return "workExperience".tr;}
static String get education{return "education".tr;}
static String get awards{return "awards".tr;}
static String get logout{return "logOut".tr;}
static String get camera{return "camera".tr;}
static String get files_manager{return "files_manager".tr;}
static String get just_now{return "just_now".tr;}
static String get min{return "min".tr;}
static String get hr{return "hr".tr;}
static String get messages{return "messages".tr;}
static String get message{return "message".tr;}
static String get is_typing{return "is_typing".tr;}
static String get today{return "today".tr;}
static String get type_message{return "type_message".tr;}
static String get online{return "online".tr;}
static String get member{return "member".tr;}
static String get members{return "members".tr;}
static String get am{return "am".tr;}
static String get pm{return "pm".tr;}
static String get attachments{return "attachments".tr;}
static String get ago{return "ago".tr;}
}*/
